### ISSUE TITLE
Library source?

### ISSUE THREAD

**Issue by camflan** [harlenalvarez/rck-documentation#1]
Wow, this documentation site looks super cool! It seems like a really useful library, and we’d love to try it out. But it looks like the repo is no longer available. Did you decide to make it private or closed-source?

**Comment by harlenalvarez** [comment]
Hey I had closed source it temporarily since I’m building the v2 under a new name.  The API will largely stay the same, but it has better support for scrollbars, mini maps, and updated touch interactions since the current lib doesn’t work on my IPad nor with the pen.  But while that is underway I can alway share the v1 repo by making you a reader.

**Comment by harlenalvarez** [comment]
I'm closing this for now, the v2 version code is here.
https://github.com/harlenalvarez/quicksketch-mono
